import { test, expect } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import path from "node:path";
test("personal saved search save, reload, reopen, rename, conflict and delete", async ({page, request}) => {
 const nav = await (await request.get("/api/workspaces")).json();
 const ws = nav.items.find((w:{type:string}) => w.type === "PERSONAL").id;
 const endpoint = `/api/workspaces/${ws}/saved-searches`;
 const initial = await (await request.get(endpoint)).json();
 expect((await request.put(endpoint,{data:{version:initial.version,searches:[]}})).ok()).toBe(true);
 await page.goto(`/w/${ws}/search?q=knowledge&path=docs&sort=newest&archived=1&page=3`);
 const region = page.getByRole("region",{name:"Saved searches"});
 await region.locator("summary").click();
 await region.getByRole("textbox",{name:"Saved search name"}).fill("Research view");
 await region.getByRole("button",{name:"Save current search",exact:true}).click();
 await expect(region.getByRole("link",{name:"Research view",exact:true})).toBeVisible();
 await page.reload(); await region.locator("summary").click();
 await region.getByRole("link",{name:"Research view",exact:true}).click();
 await expect(page).toHaveURL(url => url.searchParams.get("q") === "knowledge" && !url.searchParams.has("page"));
 expect(new URL(page.url()).searchParams.get("path")).toBe("docs");
 if(!await region.getByRole("textbox",{name:"Saved search name"}).isVisible()) await region.locator("summary").click();
 await region.getByRole("button",{name:"Rename Research view",exact:true}).click();
 await region.getByRole("textbox",{name:"Saved search name"}).fill("Weekly research");
 await region.getByRole("button",{name:"Rename search",exact:true}).click();
 await expect(region.getByRole("link",{name:"Weekly research",exact:true})).toBeVisible();
 const output = path.resolve("docs/ui-comparisons/mvp-saved-searches"); await mkdir(output,{recursive:true});
 await page.getByRole("button",{name:"Dismiss notification"}).click();
 await page.screenshot({path:path.join(output,"desktop.png"),fullPage:true,animations:"disabled"});
 await page.setViewportSize({width:390,height:844});
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:path.join(output,"mobile.png"),fullPage:true,animations:"disabled"});
 await page.setViewportSize({width:1280,height:900});
 const latest = await (await request.get(endpoint)).json();
 expect((await request.put(endpoint,{data:{version:latest.version,searches:[...latest.searches.map((s:object)=>({...s,name:"Other session"}))]}})).ok()).toBe(true);
 await region.getByRole("button",{name:"Delete Weekly research",exact:true}).click();
 await expect(region.getByRole("alert")).toContainText("Latest searches loaded");
 await expect(region.getByRole("link",{name:"Other session",exact:true})).toBeVisible();
 await page.screenshot({path:path.join(output,"conflict.png"),fullPage:true,animations:"disabled"});
 await region.getByRole("button",{name:"Delete Other session",exact:true}).click();
 await expect(region.getByRole("link",{name:"Other session",exact:true})).toHaveCount(0);
 await page.reload();await region.locator("summary").click();await expect(region.getByRole("link")).toHaveCount(0);
 const empty = await (await request.get(endpoint)).json();
 expect((await request.put(endpoint,{data:{version:empty.version,searches:[{id:"invalid",name:"Bad",filters:{q:"",scope:"workspace",source:"cross-workspace",path:"",from:"",to:"",offset:"0",sort:"relevance",archived:false}}]}})).status()).toBe(400);
});
