import { test, expect } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import { stageReadingFolder } from "./fixtures/folder-reading";
test("first folder guidance persists dismissal and rejects invalid or inaccessible preferences", async ({ page, request, browser }) => {
  const nav = await (await request.get("/api/workspaces")).json();
  const ws = nav.items.find((w: { type: string }) => w.type === "PERSONAL").id;
  const endpoint = `/api/workspaces/${ws}/onboarding`;
  const initial = await (await request.get(endpoint)).json();
  expect((await request.put(endpoint, { data: { value: { schemaVersion: 1, dismissed: false }, version: initial.version } })).ok()).toBe(true);
  await page.goto(`/w/${ws}/home`);
  // The full suite shares this workspace: earlier tests may already have imported folders.
  const emptyFolders = await page.getByText("Import a Markdown folder to bring your knowledge into My Space.", { exact: false }).isVisible();
  await expect(page.getByRole("region", { name: "Get started", exact: true })).toHaveCount(emptyFolders ? 0 : 1);
  const snapshot = await stageReadingFolder(request, { workspaceId: ws, sourceName: "Onboarding folder", fixture: "reading-flow-v1" });
  await page.goto(`/w/${ws}/sources/imports/${snapshot}`);
  await page.getByRole("button", { name: "Apply changes" }).click();
  await expect(page).toHaveURL(/\/runs\/[0-9a-f-]+$/);
  await page.goto(`/w/${ws}/home`);
  const guide = page.getByRole("region", { name: "Get started", exact: true });
  await expect(guide).toBeVisible();
  await expect(guide.getByRole("link", { name: "Read your first document" })).toBeVisible();
  await guide.getByRole("link", { name: "Prepare AI context" }).click();
  await expect(page).toHaveURL(/\/agent-context$/);
  await page.goto(`/w/${ws}/home`); await expect(guide).toBeVisible();
  await mkdir("docs/ui-comparisons/mvp-onboarding", { recursive: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: "docs/ui-comparisons/mvp-onboarding/desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "docs/ui-comparisons/mvp-onboarding/mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const before = await (await request.get(endpoint)).json();
  await guide.getByRole("button", { name: "Hide guidance" }).click();
  await expect(guide).toHaveCount(0);
  const other = await browser.newContext(); const resumed = await other.newPage();
  await resumed.goto(`${new URL(page.url()).origin}/w/${ws}/home`);
  await expect(resumed.getByRole("region", { name: "Get started", exact: true })).toHaveCount(0);
  expect((await (await request.get(endpoint)).json()).value.dismissed).toBe(true);
  expect((await request.put(endpoint, { data: { value: { schemaVersion: 1, dismissed: false }, version: before.version } })).status()).toBe(409);
  expect((await request.put(endpoint, { data: { value: { schemaVersion: 1, dismissed: true, surprise: 1 }, version: before.version + 1 } })).status()).toBe(400);
  expect((await request.get("/api/workspaces/unknown/onboarding")).status()).toBe(404);
  expect((await request.put("/api/workspaces/unknown/onboarding", { data: {} })).status()).toBe(404);
  await other.close();
});
