import { test, expect } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { readFile } from "node:fs/promises";
test.skip(process.env.KM_TEAM_WORKSPACES_ENABLED !== "false", "Runs with the personal-only rollout.");
const wait = { timeout: 15000 };
test("personal rollout: disabled teams, drafts across browsers, organize, export, restore and favorites", { tag: "@smoke-personal" }, async ({ page, browser }, testInfo) => {
  await page.goto("/"); await expect(page).toHaveURL(/\/home$/, wait);
  const navigation = await (await page.request.get("/api/workspaces")).json();
  expect(navigation.teamsOpen).toBe(false); expect(navigation.items).toHaveLength(1);
  const workspaceId = navigation.items[0].id;
  await page.getByRole("button", { name: "Workspace: My Space" }).click();
  await expect(page.getByRole("menuitem", { name: /Team workspaces.*Coming soon/ })).toBeDisabled();
  await page.keyboard.press("Escape");
  const blocked = await page.request.post("/api/workspaces", { data: { name: "Not available" } }); expect(blocked.status()).toBe(403);
  const response = await page.request.post(`/api/workspaces/${workspaceId}/documents`, { data: { title: "Personal lifecycle", markdown: "Original body" } });
  expect(response.ok()).toBe(true); const doc = await response.json();
  const href = `/w/${workspaceId}/knowledge/${doc.sourceId}/${doc.documentId}`;
  await page.goto(`${href}/edit`);
  await expect(page.getByRole("textbox", { name: "Content", exact: true })).toBeEditable(wait);
  await page.getByRole("button", { name: "Markdown", exact: true }).click();
  await page.getByRole("textbox", { name: "Markdown", exact: true }).fill("Persistent draft body");
  await expect(page.getByText("Draft saved to your account", { exact: true })).toBeVisible(wait);
  const other = await browser.newContext(); const resumed = await other.newPage();
  await resumed.goto(`${new URL(page.url()).origin}${href}/edit`);
  await expect(resumed.getByRole("textbox", { name: "Content", exact: true })).toBeEditable(wait);
  await resumed.getByRole("button", { name: "Markdown", exact: true }).click();
  await expect(resumed.getByRole("textbox", { name: "Markdown", exact: true })).toHaveValue("Persistent draft body");
  await resumed.getByRole("button", { name: "Save", exact: true }).click();
  await expect(resumed).toHaveURL(new RegExp(`${doc.documentId}$`), wait);
  await expect(resumed.getByRole("region", { name: "Document content", exact: true }).getByRole("article").getByText("Persistent draft body", { exact: true })).toBeVisible(wait);
  await page.goto(`/w/${workspaceId}/home`);
  await page.getByRole("navigation", { name: "Primary" }).getByRole("link", { name: "Knowledge" }).click();
  await expect(page).toHaveURL(new RegExp(`/w/${workspaceId}/knowledge(?:/|$)`), wait);
  await page.goto(`${href}?revision=1`);
  const content = page.getByRole("region", { name: "Document content", exact: true });
  await content.getByText("Compare revision 1 with current revision 2", { exact: true }).click();
  await expect(content.getByRole("table", { name: "Changed lines from revision 1 to 2" })).toBeVisible();
  await content.getByRole("button", { name: "Restore revision 1", exact: true }).click(); await expect(page).toHaveURL(new RegExp(`${doc.documentId}$`), wait);
  await expect(content.getByRole("article").getByText("Original body", { exact: true })).toBeVisible(wait);
  await page.goto(`/w/${workspaceId}/home`);
  await page.screenshot({ path: testInfo.outputPath("personal-home.png"), fullPage: true });
  const favoriteResponse = page.waitForResponse(r => r.url().endsWith("/personal") && r.request().method() === "PUT");
  await page.getByRole("button", { name: "Favorite: Personal lifecycle", exact: true }).first().click(); expect((await favoriteResponse).ok()).toBe(true);
  await resumed.goto(`${new URL(page.url()).origin}/w/${workspaceId}/home`);
  await expect(resumed.getByRole("button", { name: "Remove favorite: Personal lifecycle", exact: true }).first()).toBeVisible(wait);
  await page.getByRole("button", { name: "Home actions" }).click();
  const downloadPromise = page.waitForEvent("download"); await page.getByRole("menuitem", { name: "Export Markdown ZIP" }).click(); const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("my-space.zip"); const zipPath = (await download.path())!;
  expect(execFileSync("unzip", ["-t", zipPath], { encoding: "utf8" })).toContain("No errors detected");
  const zip = await readFile(zipPath);
  expect(zip.readUInt32LE(0)).toBe(0x04034b50); expect(zip.includes(Buffer.from("Original body"))).toBe(true);
  const md = await page.request.get(`/api/documents/${doc.documentId}/export`); expect(md.ok()).toBe(true); expect(await md.text()).toContain("title: Personal lifecycle");
  await other.close();
});

test("a new-note draft survives closing its tab and can be resumed from Home", { tag: "@smoke-personal" }, async ({ page, context }) => {
  await page.goto("/");
  const nav = await (await page.request.get("/api/workspaces")).json(); const workspaceId = nav.items[0].id;
  await page.goto(`/w/${workspaceId}/knowledge/new`);
  await expect(page.getByRole("textbox", { name: "Content", exact: true })).toBeEditable(wait);
  await page.getByRole("button", { name: "Markdown", exact: true }).click();
  await page.getByRole("textbox", { name: "Markdown", exact: true }).fill("# New persistent note\n\nClose and resume");
  await expect(page.getByText("Draft saved to your account", { exact: true })).toBeVisible(wait);
  await page.close();
  const next = await context.newPage(); await next.goto("/");
  await next.getByRole("tab", { name: /^Drafts/ }).click();
  const draft = next.getByRole("tabpanel")
    .getByRole("link").filter({ has: next.getByText("New persistent note", { exact: true }) });
  await expect(draft).toHaveAttribute("href", `/w/${workspaceId}/knowledge/new`);
  await draft.click();
  await expect(next.getByRole("textbox", { name: "Content", exact: true })).toBeEditable(wait);
  await next.getByRole("button", { name: "Markdown", exact: true }).click();
  await expect(next.getByRole("textbox", { name: "Markdown", exact: true })).toHaveValue("# New persistent note\n\nClose and resume");
  await next.getByRole("button", { name: "Create document", exact: true }).click();
  await expect(next).toHaveURL(/\/knowledge\/[^/]+\/[^/]+$/, wait);
  const items = await (await next.request.get(`/api/workspaces/${workspaceId}/personal`)).json();
  expect(items.some((i: { key: string }) => i.key === "draft:new")).toBe(false);
});
