import { afterAll, beforeAll, beforeEach, expect, it } from "vitest";
import type { Pool } from "mariadb";
import { databaseConfig } from "@/infrastructure/database/mariadb/config";
import { createDatabasePool } from "@/infrastructure/database/mariadb/pool";
import { MariaDbUnitOfWork } from "@/infrastructure/database/mariadb/transaction";
import { CreateFolderImportService } from "@/modules/sources/application/create-folder-import";
import { UploadFolderImportEntriesService } from "@/modules/sources/application/upload-folder-import-entries";
import { FinalizeFolderImportService } from "@/modules/sources/application/finalize-folder-import";
import { ApplyFolderImportService } from "@/modules/sources/application/apply-folder-import";
import { GetImportScopeService } from "@/modules/sources/application/get-import-scope";
import { AgentContextService } from "@/modules/knowledge/application/agent-context-service";
import { parseSearchFilters } from "@/modules/knowledge/domain/search-filters";
import { createSourceFixture, fixtureCaller, fixtureIdentity } from "../fixtures/knowledge";
import { PersonalWorkspaceService } from "@/modules/workspaces/application/personal-workspace-service";
let pool: Pool;
beforeAll(() => { pool = createDatabasePool(databaseConfig("test")); });
afterAll(async () => { await pool.end(); });
beforeEach(async () => { await pool.query("DELETE FROM source_import_snapshots"); });
const caller = fixtureCaller();
async function stage(workspaceId: string, paths: string[], scopePaths: string[], sourceId?: string, expectedSourceVersion?: number) {
  const uow = new MariaDbUnitOfWork(pool);
  const bytes = new TextEncoder().encode("# Context guide\n\nMVP search content.");
  const base = { rootName: "wiki", manifest: paths.map((path, i) => ({ uploadKey: `m${i}`, relativePath: path, kind: "MARKDOWN" as const, size: bytes.length })), importScope: { paths: scopePaths, excludedCount: 1 } };
  const create = new CreateFolderImportService(uow);
  const session = sourceId ? await create.createResync(caller, { ...base, sourceId, expectedSourceVersion }) : await create.createInitial(caller, { ...base, workspaceId, sourceName: "MVP folder" });
  await new UploadFolderImportEntriesService(uow).upload(caller, { snapshotId: session.snapshotId, entries: paths.map((_, i) => ({ uploadKey: `m${i}`, bytes })) });
  const preview = await new FinalizeFolderImportService(uow).finalize(caller, session.snapshotId);
  return { session, preview, uow };
}
it("persists first-import rules only with Apply and uses the guarded source version", async () => {
  const fixture = await createSourceFixture(pool);
  const { session, preview, uow } = await stage(fixture.workspaceId, ["docs/a.md"], ["private"]);
  expect(preview.importScope).toEqual({ paths: ["private"], previousPaths: [], excludedCount: 1 });
  const result = await new ApplyFolderImportService(uow).apply(caller, session.snapshotId);
  if (result.kind !== "APPLIED") throw new Error("Expected Apply");
  expect(await new GetImportScopeService(uow).get(caller, result.sourceId)).toEqual({ paths: ["private"], configured: true, syncVersion: 1 });
  await expect(new CreateFolderImportService(uow).createResync(caller, { sourceId: result.sourceId, rootName: "wiki", manifest: [{ uploadKey: "a", relativePath: "docs/a.md", kind: "MARKDOWN", size: 0 }], importScope: { paths: [], excludedCount: 0 }, expectedSourceVersion: 0 })).rejects.toMatchObject({ code: "SOURCE_VERSION_CONFLICT" });
  const next = await stage(fixture.workspaceId, ["docs/a.md"], ["tmp"], result.sourceId, 1);
  expect(next.preview.importScope?.previousPaths).toEqual(["private"]);
  await expect(new ApplyFolderImportService(uow, { failurePoint: "before-run" }).apply(caller, next.session.snapshotId)).rejects.toMatchObject({ code: "TEST_IMPORT_FAILURE" });
  expect((await new GetImportScopeService(uow).get(caller, result.sourceId)).paths).toEqual(["private"]);
  await new ApplyFolderImportService(uow).apply(caller, next.session.snapshotId);
  expect((await new GetImportScopeService(uow).get(caller, result.sourceId)).paths).toEqual(["tmp"]);
});
it("filters literal path boundaries and inclusive date ranges using content revision times", async () => {
  const fixture = await createSourceFixture(pool);
  const { session, uow } = await stage(fixture.workspaceId, ["doc%_!/a.md", "doc%_!extra/b.md", "other/c.md"], []);
  const result = await new ApplyFolderImportService(uow).apply(caller, session.snapshotId); if (result.kind !== "APPLIED") throw new Error("Expected Apply");
  await pool.query("UPDATE knowledge_revisions r JOIN knowledge_documents d ON d.current_revision_id=r.id SET r.created_at=? WHERE d.source_id=?", [new Date("2026-10-03T16:00:00Z"), result.sourceId]);
  const criteria = { terms: [] as string[], workspaceIds: [fixture.workspaceId], sourceId: result.sourceId, includeArchived: false, limit: 21, offset: 0, filters: parseSearchFilters({ path: "doc%_!", from: "2026-10-04", to: "2026-10-04", offset: "480", sort: "newest" }) };
  const hits = await uow.run(r => r.search.search(criteria));; expect(hits).toHaveLength(1);
  await pool.query("UPDATE knowledge_revisions r JOIN knowledge_documents d ON d.current_revision_id=r.id SET r.created_at=? WHERE d.id=?", [new Date("2026-10-04T16:00:00Z"), hits[0].documentId]);
  expect(await uow.run(r => r.search.search(criteria))).toHaveLength(0);
  expect(await uow.run(r => r.search.search({ ...criteria, workspaceIds: [] }))).toHaveLength(0);
});
it("builds a personal context with saved paths and rejects mixed-workspace and archived selections", async () => {
  const fixture = await createSourceFixture(pool);
  const uow = new MariaDbUnitOfWork(pool);
  const { workspace } = await new PersonalWorkspaceService(uow).ensurePersonalWorkspace(fixtureIdentity.id);
  const first = await stage(workspace.id, ["docs/agent.md", "docs/ref.md"], []);
  const result = await new ApplyFolderImportService(uow).apply(caller, first.session.snapshotId); if (result.kind !== "APPLIED") throw new Error("Expected Apply");
  const docs = await pool.query<{ id: string }[]>("SELECT id FROM knowledge_documents WHERE source_id=? ORDER BY id", [result.sourceId]);
  const service = new AgentContextService(uow);
  const bundle = await service.build(caller, workspace.id, docs.map(d => d.id)); expect(bundle.documentCount).toBe(2); expect(bundle.markdown).toContain("docs/agent.md"); expect(bundle.markdown).toContain("?revision=1");
  const other = await stage(fixture.workspaceId, ["foreign.md"], []); const foreign = await new ApplyFolderImportService(uow).apply(caller, other.session.snapshotId); if (foreign.kind !== "APPLIED") throw new Error("Expected Apply");
  const foreignDocs = await pool.query<{ id: string }[]>("SELECT id FROM knowledge_documents WHERE source_id=?", [foreign.sourceId]);
  await expect(service.build(caller, workspace.id, [docs[0].id, foreignDocs[0].id])).rejects.toMatchObject({ code: "DOCUMENT_NOT_FOUND" });
  await pool.query("UPDATE knowledge_tree_nodes SET status='ARCHIVED',archived_by=?,archived_at=NOW() WHERE document_id=?", [fixtureIdentity.id, docs[0].id]);
  await expect(service.build(caller, workspace.id, [docs[0].id])).rejects.toMatchObject({ code: "DOCUMENT_NOT_FOUND" });
});
