"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { formatDateTime } from "@/lib/format-date";
import type { AuditPage } from "@/server/workspace-admin";
import { GovernanceError, governanceFailure, governanceRequest, type GovernanceFailure } from "./governance-error";
export function AuditSettings({ workspaceId, initialPage }: { workspaceId: string; initialPage: AuditPage }) {
  const [page, setPage] = useState(initialPage); const [busy, setBusy] = useState(false); const [error, setError] = useState<GovernanceFailure | null>(null);
  useEffect(() => setPage(initialPage), [initialPage]);
  return <section className="space-y-4"><h2 className="text-title font-semibold">Audit</h2>{page.items.length === 0 && <p>No audit events yet.</p>}<ol className="space-y-3">{page.items.map((item) => <li key={item.id} className="rounded-md border border-kh-border p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{item.summary}</p><time className="text-caption text-kh-text-muted" dateTime={item.createdAt}>{formatDateTime(new Date(item.createdAt))}</time></div><p className="mt-1 text-body">Actor: {item.actorName ?? "Unknown actor"} · {item.eventType}</p><p className="text-body">Target: {item.targetType}{item.targetId ? ` · ${item.targetId}` : ""}</p>{(item.before || item.after) && <details className="mt-2 text-body"><summary className="cursor-pointer">Before / after details</summary><pre className="mt-2 overflow-x-auto whitespace-pre-wrap break-all">{JSON.stringify({ before: item.before, after: item.after }, null, 2)}</pre></details>}</li>)}</ol><GovernanceError error={error} />{page.nextCursor && <Button variant="secondary" disabled={busy} onClick={async () => { setBusy(true); setError(null); try { const next = await governanceRequest<AuditPage>(`/api/workspaces/${workspaceId}/audit?cursor=${encodeURIComponent(page.nextCursor!)}`); setPage((current) => ({ items: [...current.items, ...next.items.filter((item) => !current.items.some((existing) => existing.id === item.id))], nextCursor: next.nextCursor })); } catch (failure) { setError(governanceFailure(failure)); } finally { setBusy(false); } }}>{busy ? "Loading…" : "Load more"}</Button>}</section>;
}
