import type { Migration } from "./types";

/**
 * The ten canonical Phase 0 domain tables.  Foreign keys intentionally use
 * MariaDB's native UUID type; the application supplies UUIDv7 values.
 */
export const coreMigration: Migration = {
  version: 1,
  name: "core-knowledge-workspace",
  statements: [
    `CREATE TABLE users (
      id UUID NOT NULL,
      emp_id VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      name VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      org_code VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      PRIMARY KEY (id),
      CONSTRAINT uq_users_emp_id UNIQUE (emp_id),
      CONSTRAINT ck_users_emp_id_nonempty CHECK (CHAR_LENGTH(emp_id) > 0),
      CONSTRAINT ck_users_name_nonempty CHECK (CHAR_LENGTH(name) > 0),
      CONSTRAINT ck_users_org_nonempty CHECK (CHAR_LENGTH(org_code) > 0)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE workspaces (
      id UUID NOT NULL,
      name VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      PRIMARY KEY (id),
      CONSTRAINT ck_workspaces_name_nonempty CHECK (CHAR_LENGTH(name) > 0)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE workspace_memberships (
      workspace_id UUID NOT NULL,
      user_id UUID NOT NULL,
      created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      PRIMARY KEY (workspace_id, user_id),
      CONSTRAINT fk_memberships_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      KEY idx_memberships_user_workspace (user_id, workspace_id)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE knowledge_sources (
      id UUID NOT NULL,
      name VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      workspace_id UUID NOT NULL,
      source_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      ownership VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
      sync_version INT UNSIGNED NOT NULL DEFAULT 0,
      created_by UUID NOT NULL,
      updated_by UUID NULL,
      archived_by UUID NULL,
      archived_at DATETIME(6) NULL,
      created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      PRIMARY KEY (id),
      CONSTRAINT fk_sources_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_sources_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_sources_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_sources_archived_by FOREIGN KEY (archived_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT ck_sources_name_nonempty CHECK (CHAR_LENGTH(name) > 0),
      CONSTRAINT ck_sources_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
      CONSTRAINT ck_sources_type_ownership CHECK ((source_type = 'FOLDER_SYNC' AND ownership = 'SOURCE_MANAGED') OR (source_type IN ('FILE_UPLOAD', 'HUB') AND ownership = 'HUB_MANAGED')),
      CONSTRAINT ck_sources_lifecycle_provenance CHECK ((status = 'ACTIVE' AND archived_by IS NULL AND archived_at IS NULL) OR (status = 'ARCHIVED' AND archived_by IS NOT NULL AND archived_at IS NOT NULL)),
      KEY idx_sources_workspace_status (workspace_id, status)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE knowledge_documents (
      id UUID NOT NULL,
      source_id UUID NOT NULL,
      current_revision_id UUID NULL,
      status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
      created_by UUID NOT NULL,
      updated_by UUID NULL,
      archived_by UUID NULL,
      archived_at DATETIME(6) NULL,
      created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      PRIMARY KEY (id),
      CONSTRAINT uq_documents_source_id UNIQUE (source_id, id),
      CONSTRAINT fk_documents_source FOREIGN KEY (source_id) REFERENCES knowledge_sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_documents_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_documents_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_documents_archived_by FOREIGN KEY (archived_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT ck_documents_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
      CONSTRAINT ck_documents_lifecycle_provenance CHECK ((status = 'ACTIVE' AND archived_by IS NULL AND archived_at IS NULL) OR (status = 'ARCHIVED' AND archived_by IS NOT NULL AND archived_at IS NOT NULL)),
      KEY idx_documents_source_status (source_id, status)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE knowledge_revisions (
      id UUID NOT NULL,
      document_id UUID NOT NULL,
      revision_no INT UNSIGNED NOT NULL,
      title VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      markdown LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      metadata JSON NOT NULL,
      content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      created_by UUID NOT NULL,
      created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      PRIMARY KEY (id),
      CONSTRAINT uq_revisions_document_no UNIQUE (document_id, revision_no),
      CONSTRAINT uq_revisions_document_id UNIQUE (document_id, id),
      CONSTRAINT fk_revisions_document FOREIGN KEY (document_id) REFERENCES knowledge_documents(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_revisions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT ck_revisions_no_positive CHECK (revision_no > 0),
      CONSTRAINT ck_revisions_title_nonempty CHECK (CHAR_LENGTH(title) > 0),
      CONSTRAINT ck_revisions_metadata_json CHECK (JSON_VALID(metadata)),
      KEY idx_revisions_document_created (document_id, created_at)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE knowledge_tree_nodes (
      id UUID NOT NULL,
      source_id UUID NOT NULL,
      parent_id UUID NULL,
      node_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      name VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
      document_id UUID NULL,
      position INT UNSIGNED NOT NULL DEFAULT 0,
      status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
      updated_by UUID NULL,
      archived_by UUID NULL,
      archived_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      CONSTRAINT uq_tree_source_id UNIQUE (source_id, id),
      CONSTRAINT uq_tree_one_document UNIQUE (document_id),
      CONSTRAINT fk_tree_source FOREIGN KEY (source_id) REFERENCES knowledge_sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_tree_parent_same_source FOREIGN KEY (source_id, parent_id) REFERENCES knowledge_tree_nodes(source_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_tree_document_same_source FOREIGN KEY (source_id, document_id) REFERENCES knowledge_documents(source_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_tree_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_tree_archived_by FOREIGN KEY (archived_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT ck_tree_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
      CONSTRAINT ck_tree_type_shape CHECK ((node_type = 'FOLDER' AND name IS NOT NULL AND CHAR_LENGTH(name) > 0 AND document_id IS NULL) OR (node_type = 'DOCUMENT' AND name IS NULL AND document_id IS NOT NULL)),
      CONSTRAINT ck_tree_node_type CHECK (node_type IN ('FOLDER', 'DOCUMENT')),
      CONSTRAINT ck_tree_lifecycle_provenance CHECK ((status = 'ACTIVE' AND archived_by IS NULL AND archived_at IS NULL) OR (status = 'ARCHIVED' AND archived_by IS NOT NULL AND archived_at IS NOT NULL)),
      KEY idx_tree_source_parent_position (source_id, parent_id, status, position)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE source_entries (
      id UUID NOT NULL,
      source_id UUID NOT NULL,
      external_id VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
      source_path TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      entry_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      document_id UUID NULL,
      status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
      updated_by UUID NULL,
      archived_by UUID NULL,
      archived_at DATETIME(6) NULL,
      first_seen_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      last_seen_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      PRIMARY KEY (id),
      CONSTRAINT uq_entries_source_external UNIQUE (source_id, external_id),
      CONSTRAINT uq_entries_source_document UNIQUE (source_id, document_id),
      CONSTRAINT fk_entries_source FOREIGN KEY (source_id) REFERENCES knowledge_sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_entries_document_same_source FOREIGN KEY (source_id, document_id) REFERENCES knowledge_documents(source_id, id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_entries_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_entries_archived_by FOREIGN KEY (archived_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT ck_entries_external_nonempty CHECK (external_id IS NULL OR CHAR_LENGTH(external_id) > 0),
      CONSTRAINT ck_entries_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
      CONSTRAINT ck_entries_type_shape CHECK ((entry_type = 'FOLDER' AND document_id IS NULL) OR (entry_type = 'DOCUMENT' AND document_id IS NOT NULL)),
      CONSTRAINT ck_entries_lifecycle_provenance CHECK ((status = 'ACTIVE' AND archived_by IS NULL AND archived_at IS NULL) OR (status = 'ARCHIVED' AND archived_by IS NOT NULL AND archived_at IS NOT NULL)),
      KEY idx_entries_source_status (source_id, status)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE knowledge_assets (
      id UUID NOT NULL,
      source_id UUID NOT NULL,
      source_path TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      mime_type VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
      content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      metadata JSON NOT NULL,
      created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      PRIMARY KEY (id),
      CONSTRAINT fk_assets_source FOREIGN KEY (source_id) REFERENCES knowledge_sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT ck_assets_metadata_json CHECK (JSON_VALID(metadata))
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE sync_runs (
      id UUID NOT NULL,
      source_id UUID NOT NULL,
      triggered_by UUID NOT NULL,
      based_on_version INT UNSIGNED NOT NULL,
      result_version INT UNSIGNED NULL,
      status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      summary JSON NOT NULL,
      started_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      completed_at DATETIME(6) NULL,
      PRIMARY KEY (id),
      CONSTRAINT fk_sync_runs_source FOREIGN KEY (source_id) REFERENCES knowledge_sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_sync_runs_triggered_by FOREIGN KEY (triggered_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT ck_sync_runs_status CHECK (status IN ('PREVIEWED', 'APPLIED', 'FAILED')),
      CONSTRAINT ck_sync_runs_result_shape CHECK ((status = 'APPLIED' AND result_version IS NOT NULL AND completed_at IS NOT NULL) OR (status IN ('PREVIEWED', 'FAILED') AND result_version IS NULL)),
      CONSTRAINT ck_sync_runs_summary_json CHECK (JSON_VALID(summary)),
      KEY idx_sync_runs_source_started (source_id, started_at)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  ],
};
