import type { Migration } from "./types";

export const phase2ImportStagingMigration: Migration = {
  version: 6,
  name: "phase-2-import-staging",
  statements: [
    `CREATE TABLE source_import_snapshots (
      id UUID NOT NULL,
      workspace_id UUID NOT NULL,
      source_id UUID NULL,
      based_on_version INT UNSIGNED NULL,
      created_by UUID NOT NULL,
      root_name VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      proposed_source_name VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
      adapter_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      adapter_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      plan_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      state VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      manifest_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      snapshot_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      plan_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      has_blockers BOOLEAN NOT NULL DEFAULT FALSE,
      summary JSON NULL,
      plan JSON NULL,
      created_at DATETIME(6) NOT NULL,
      finalized_at DATETIME(6) NULL,
      expires_at DATETIME(6) NOT NULL,
      applied_at DATETIME(6) NULL,
      stale_at DATETIME(6) NULL,
      result_source_id UUID NULL,
      result_version INT UNSIGNED NULL,
      PRIMARY KEY (id),
      CONSTRAINT fk_import_snapshots_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_import_snapshots_source FOREIGN KEY (source_id) REFERENCES knowledge_sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_import_snapshots_creator FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT fk_import_snapshots_result_source FOREIGN KEY (result_source_id) REFERENCES knowledge_sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
      CONSTRAINT ck_import_snapshots_root_name CHECK (CHAR_LENGTH(root_name) > 0),
      CONSTRAINT ck_import_snapshots_adapter CHECK (adapter_type = 'GENERIC_MARKDOWN_FOLDER' AND adapter_version = 'phase2:v1' AND plan_version = 'phase2:v1'),
      CONSTRAINT ck_import_snapshots_state CHECK (state IN ('BUILDING','READY','APPLIED','STALE')),
      CONSTRAINT ck_import_snapshots_binding CHECK ((source_id IS NULL AND based_on_version IS NULL AND proposed_source_name IS NOT NULL AND CHAR_LENGTH(proposed_source_name) > 0) OR (source_id IS NOT NULL AND based_on_version IS NOT NULL AND proposed_source_name IS NULL)),
      CONSTRAINT ck_import_snapshots_summary_json CHECK (summary IS NULL OR JSON_VALID(summary)),
      CONSTRAINT ck_import_snapshots_plan_json CHECK (plan IS NULL OR JSON_VALID(plan)),
      CONSTRAINT ck_import_snapshots_state_shape CHECK ((state = 'BUILDING' AND finalized_at IS NULL AND applied_at IS NULL AND stale_at IS NULL AND result_source_id IS NULL AND result_version IS NULL) OR (state = 'READY' AND finalized_at IS NOT NULL AND snapshot_hash IS NOT NULL AND plan_hash IS NOT NULL AND summary IS NOT NULL AND plan IS NOT NULL AND applied_at IS NULL AND stale_at IS NULL AND result_source_id IS NULL AND result_version IS NULL) OR (state = 'APPLIED' AND finalized_at IS NOT NULL AND snapshot_hash IS NOT NULL AND plan_hash IS NOT NULL AND summary IS NOT NULL AND plan IS NOT NULL AND applied_at IS NOT NULL AND stale_at IS NULL AND result_source_id IS NOT NULL AND result_version IS NOT NULL) OR (state = 'STALE' AND finalized_at IS NOT NULL AND snapshot_hash IS NOT NULL AND plan_hash IS NOT NULL AND summary IS NOT NULL AND plan IS NOT NULL AND applied_at IS NULL AND stale_at IS NOT NULL AND result_source_id IS NULL AND result_version IS NULL)),
      KEY idx_import_snapshots_creator_state (created_by, state),
      KEY idx_import_snapshots_source_created (source_id, created_at),
      KEY idx_import_snapshots_workspace_created (workspace_id, created_at),
      KEY idx_import_snapshots_state_expires (state, expires_at)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE source_import_snapshot_entries (
      id UUID NOT NULL,
      snapshot_id UUID NOT NULL,
      upload_key VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      client_relative_path TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
      source_path TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
      source_path_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      entry_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      upload_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      declared_size BIGINT UNSIGNED NOT NULL,
      source_file_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      raw_markdown LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
      resolved_title VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
      title_source VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NULL,
      markdown LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
      metadata JSON NULL,
      revision_content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      reconciliation_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      mime_type VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
      asset_content_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
      asset_size BIGINT UNSIGNED NULL,
      asset_last_modified DATETIME(6) NULL,
      diagnostics JSON NOT NULL,
      preview_change JSON NULL,
      PRIMARY KEY (id),
      CONSTRAINT fk_import_entries_snapshot FOREIGN KEY (snapshot_id) REFERENCES source_import_snapshots(id) ON UPDATE RESTRICT ON DELETE CASCADE,
      CONSTRAINT ck_import_entries_upload_key CHECK (CHAR_LENGTH(upload_key) > 0),
      CONSTRAINT ck_import_entries_client_path CHECK (CHAR_LENGTH(client_relative_path) > 0),
      CONSTRAINT ck_import_entries_type CHECK (entry_type IN ('DOCUMENT','ASSET')),
      CONSTRAINT ck_import_entries_upload_status CHECK (upload_status IN ('PENDING','RECEIVED')),
      CONSTRAINT ck_import_entries_title_source CHECK (title_source IS NULL OR title_source IN ('FRONTMATTER','H1','FILENAME')),
      CONSTRAINT ck_import_entries_metadata_json CHECK (metadata IS NULL OR JSON_VALID(metadata)),
      CONSTRAINT ck_import_entries_diagnostics_json CHECK (JSON_VALID(diagnostics)),
      CONSTRAINT ck_import_entries_preview_json CHECK (preview_change IS NULL OR JSON_VALID(preview_change)),
      CONSTRAINT uq_import_entries_snapshot_upload UNIQUE (snapshot_id, upload_key),
      CONSTRAINT uq_import_entries_snapshot_path_hash UNIQUE (snapshot_id, source_path_hash),
      KEY idx_import_entries_snapshot_upload (snapshot_id, upload_status)
    ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  ],
};
