import { WorkspaceEmptyIllustration } from "@/components/knowledge/workspace-empty-illustration";
import { ReadingActivityView } from "./reading-activity";
import { BarChart3 } from "lucide-react";
import { EmptyState } from "@/components/ui/empty-state";
import { WorkspaceContentActions } from "@/components/knowledge/workspace-content-actions";
import { buttonClasses } from "@/components/ui/button";
import Link from "next/link";
import {ArrowRight,Plus,PenLine,Archive} from "lucide-react";
import type {PersonalProfile} from "@/modules/personal/domain/personal-profile";
import {Timestamp} from "@/components/ui/timestamp";
import {ProfileRefresh} from "./profile-refresh";
import {PageHeader} from "@/components/shell/page-header";
import styles from "./profile.module.css";
const viewedLabel=(viewed:number,total:number)=>total?`${viewed} of ${total} viewed`:"0 documents";
const viewedWidth=(viewed:number,total:number)=>`${total?viewed/total*100:0}%`;
export function PersonalProfileView({profile:p}:{profile:PersonalProfile}){
 const base=`/w/${p.workspaceId}`,profile=`${base}/profile`,articles=(filter:string)=>`${profile}/articles?filter=${filter}&days=${p.days}`;
 const showStats = p.counts.articles > 0 || p.counts.archived > 0 || p.counts.folders > 0 || p.sync.pending > 0 || p.sync.failed > 0 || p.legacyChangesUnavailable || p.reading.articles > 0;
 const otherCount=p.counts.folders-p.sources.length,otherArticles=p.counts.synced-p.sources.reduce((sum,s)=>sum+s.articles,0),otherViewed=p.counts.syncedBrowsed-p.sources.reduce((sum,s)=>sum+s.viewed,0),max=Math.max(1,...p.sources.map(s=>s.articles),otherArticles);
 return <main className={`kh-page pb-6 ${styles.profile}`}>
  <PageHeader location="My Space" locationHref={`${base}/home`} title="Insights" description="Understand how your personal knowledge grows and changes." actions={<nav className="flex items-center gap-1 rounded-md bg-kh-bg-subtle p-1" aria-label="Statistics period">{[7,30].map(days=><Link key={days} href={`${profile}?days=${days}`} scroll={false} aria-current={p.days===days?"page":undefined} className={`kh-focus-ring inline-flex h-8 items-center rounded-md px-3 text-body-sm font-medium ${p.days===days ? "bg-kh-bg text-kh-text" : "text-kh-text-muted hover:text-kh-text"}`}>{days} days</Link>)}</nav>}/>

  {p.counts.articles===0?<EmptyState icon={BarChart3} illustration={p.sync.pending === 0 && p.counts.archived === 0 ? <WorkspaceEmptyIllustration kind="insights" /> : undefined} title={p.sync.pending > 0 ? "Apply your preview to see insights" : p.counts.archived > 0 ? "No active documents to measure" : "See your knowledge grow"} description={p.sync.pending > 0 ? "A preview is waiting for review. Apply it to add documents and start recording folder changes here." : p.counts.archived > 0 ? "Archived documents are excluded from these totals. Browse them or add active documents to see your current knowledge." : "After you save documents, this page shows your knowledge composition, folder sync status and recorded folder changes."} action={p.sync.pending > 0 ? <Link className={buttonClasses()} href={`${profile}/sync?filter=pending`}>Review pending previews</Link> : p.counts.archived > 0 ? <Link className={buttonClasses({variant:"secondary"})} href={articles("archived")}>Browse archived documents</Link> : <WorkspaceContentActions workspaceId={p.workspaceId} />} />:null}
  {showStats ? <>
  <div className={styles.pair}><section aria-labelledby="knowledge-composition"><h2 className={styles.sectiontitle} id="knowledge-composition">Your knowledge</h2><p className={styles.caption}>{p.counts.articles.toLocaleString("en-US")} active documents in My Space.</p><div className={styles.composition} role="img" aria-label={`${p.counts.synced} synced documents and ${p.counts.notes} personal notes`}><div className={styles.synced} style={{width:`${p.counts.articles?p.counts.synced/p.counts.articles*100:0}%`}}/><div className={styles.notes} style={{width:`${p.counts.articles?p.counts.notes/p.counts.articles*100:0}%`}}/></div><div className={styles.legend}><Link className="kh-focus-ring rounded" href={articles("synced")}><i className={styles.dot}/>Synced<strong>{p.counts.synced}</strong></Link><Link className="kh-focus-ring rounded" href={articles("notes")}><i className={`${styles.dot} ${styles.dotSoft}`}/>Personal notes<strong>{p.counts.notes}</strong></Link></div><Link className={`${styles.archive} kh-focus-ring rounded`} href={articles("unread")}><span>Unread updates</span><strong>{p.counts.unread}</strong></Link><Link className={`${styles.archive} ${styles.archiveNext} kh-focus-ring rounded`} href={articles("archived")}><span>Archived documents</span><strong>{p.counts.archived}</strong></Link><p className={styles.small}>Archived documents and drafts are excluded from the active total.</p></section>
  <section aria-labelledby="source-distribution"><h2 className={styles.sectiontitle} id="source-distribution">Where your knowledge lives</h2><p className={styles.caption}>{p.counts.synced} documents across {p.counts.folders} synced folders.</p>{p.sources.map(s=><Link key={s.sourceId} className={`${styles.source} kh-focus-ring`} href={`${base}/knowledge/${s.sourceId}`}><div className={styles.sourceLabel}><span className={styles.sourceName} title={s.name}>{s.name}</span><span className={styles.sourceCount}>{viewedLabel(s.viewed,s.articles)}</span></div><div className={styles.track}><div className={styles.fill} style={{width:`${s.articles/max*100}%`}}><div className={styles.fillViewed} style={{width:viewedWidth(s.viewed,s.articles)}}/></div></div><p className={styles.lastSync}>{s.lastSyncedAt?<>Last synced <Timestamp value={s.lastSyncedAt} variant="relative"/></>:"Never synced"}</p></Link>)}{otherCount>0?<Link className={`${styles.source} kh-focus-ring`} href={`${profile}/sync?filter=folders`}><div className={styles.sourceLabel}><span>{otherCount} other folders</span><span className={styles.sourceCount}>{viewedLabel(otherViewed,otherArticles)}</span></div><div className={styles.track}><div className={styles.fill} style={{width:`${otherArticles/max*100}%`}}><div className={styles.fillViewed} style={{width:viewedWidth(otherViewed,otherArticles)}}/></div></div></Link>:null}{!p.sources.length?<p className={styles.empty}>Your synced folders will appear here.</p>:null}</section></div>
  <ReadingActivityView activity={p.reading} cumulative={p.counts.browsed} total={p.counts.articles} days={p.days}/>
  <section className={styles.activity} aria-labelledby="recent-changes"><div className={styles.sectionhead}><h2 className={styles.sectiontitle} id="recent-changes">Recent changes</h2></div><p className={styles.caption}>Recorded folder changes in the past {p.days} days.</p><div className={styles.changeStats}>{[{name:"Added",count:p.changes.added,filter:"added",Icon:Plus},{name:"Updated",count:p.changes.updated,filter:"updated",Icon:PenLine},{name:"Archived",count:p.changes.archived,filter:"recent-archived",Icon:Archive}].map(({name,count,filter,Icon})=><Link key={name} className={`${styles.change} kh-focus-ring`} href={articles(filter)} aria-label={`${name}: ${count} documents in the past ${p.days} days`}><div className={styles.changeIcon}><Icon size={16} aria-hidden="true"/></div><div><div className={styles.value}>{count}</div><div className={styles.changeName}>{name}</div></div></Link>)}</div><p className={styles.small}>Distinct documents in each category. A document may appear in more than one category.</p>{p.legacyChangesUnavailable?<p role="status" className={styles.legacy}>Older syncs in this period have no document-level history. These counts include recorded changes only.</p>:null}</section>
  <section className={styles.sync} aria-labelledby="sync-overview"><h2 className={styles.sectiontitle} id="sync-overview">Sync overview</h2><p className={styles.caption}>Latest completed attempt for each active folder.</p><div className={styles.syncGrid}>{[{name:"Last sync successful",count:p.sync.successful,filter:"successful",unit:p.sync.successful===1?"folder":"folders",color:""},{name:"Last sync failed",count:p.sync.failed,filter:"failed",unit:p.sync.failed===1?"folder":"folders",color:styles.warning},{name:"Awaiting Apply",count:p.sync.pending,filter:"pending",unit:p.sync.pending===1?"preview":"previews",color:styles.pending}].map(s=><Link key={s.filter} className={`${styles.syncItem} kh-focus-ring`} href={`${profile}/sync?filter=${s.filter}`} aria-label={`${s.name}: ${s.count} ${s.unit}`}><div className={styles.syncLabel}><i className={`${styles.statusDot} ${s.color}`}/>{s.name}</div><div className={styles.syncCount}><b>{s.count}</b>{s.unit}<ArrowRight size={12} aria-hidden="true"/></div></Link>)}</div><p className={styles.small}>Pending previews are counted separately from completed sync attempts.</p>{p.sync.neverSynced>0?<p className={styles.small}>{p.sync.neverSynced} {p.sync.neverSynced===1?"folder has":"folders have"} no completed sync attempt yet.</p>:null}</section>
  </> : null}
  <footer className={styles.footer}><span>My Space only · Updated <Timestamp value={p.generatedAt}/></span><ProfileRefresh/></footer>
  {showStats ? <details className={styles.definitions}><summary className="kh-focus-ring">How counts work</summary><dl><dt>Documents</dt><dd>Saved documents in active sources. Drafts and archived documents are excluded. Personal notes include Hub notes and uploaded Markdown.</dd><dt>Reading activity</dt><dd>Documents opened in My Space during the selected calendar days, including today, in Taipei time (UTC+8). Each document counts once per day and once across the period; daily totals may sum to more than the period total. Historical activity is retained after archiving. Tracking starts when the reading activity migration is applied; earlier visits cannot be reconstructed.</dd><dt>All-time library views</dt><dd>Active documents you have opened, counted once across all time. Archived documents and sources are excluded.</dd><dt>Viewed</dt><dd>Active documents in a synced folder that you have opened at least once, at any revision. A document you opened and a sync later updated is both viewed and an unread update.</dd><dt>Archived documents</dt><dd>Archived documents and documents in archived sources, counted once.</dd><dt>Unread updates</dt><dd>Active synced documents with a recorded change on their latest revision that you have not read. Each document is counted once. Older imports without recorded changes are excluded.</dd><dt>Recent changes</dt><dd>Distinct documents added, updated or archived by recorded folder syncs in the past {p.days} × 24 hours. This is separate from the document’s current archived state.</dd><dt>Awaiting Apply</dt><dd>Your unexpired previews without blockers. Existing-source previews must match the current source version. New-folder previews are included.</dd><dt>Updated time</dt><dd>When these statistics were requested. Each folder’s last successful sync time is displayed separately.</dd></dl></details> : null}
 </main>;
}
