import Link from "next/link";
import {ArrowRight,Plus,PenLine,Archive} from "lucide-react";
import type {PersonalProfile} from "@/modules/personal/domain/personal-profile";
import {Timestamp} from "@/components/ui/timestamp";
import {ProfileRefresh} from "./profile-refresh";
import styles from "./profile.module.css";
export function PersonalProfileView({profile:p}:{profile:PersonalProfile}){
 const base=`/w/${p.workspaceId}`,profile=`${base}/profile`,articles=(filter:string)=>`${profile}/articles?filter=${filter}&days=${p.days}`;
 const otherCount=p.counts.folders-p.sources.length,otherArticles=p.counts.synced-p.sources.reduce((sum,s)=>sum+s.articles,0),max=Math.max(1,...p.sources.map(s=>s.articles),otherArticles);
 return <main className={styles.profile}>
  <header className={styles.insightsHeader}><div><h1 className={styles.name}>Insights</h1><p className={styles.subtitle}>Understand how your personal knowledge grows and changes.</p></div><nav className={styles.segment} aria-label="Statistics period">{[7,30].map(days=><Link key={days} href={`${profile}?days=${days}`} scroll={false} aria-current={p.days===days?"page":undefined} className="kh-focus-ring">{days} days</Link>)}</nav></header>
  {p.counts.articles===0?<p className={styles.empty}>Build your personal knowledge space.<br/><Link className={`${styles.import} kh-focus-ring`} href={`${base}/sources/import`}>Import your first folder</Link></p>:null}
  <div className={styles.pair}><section aria-labelledby="knowledge-composition"><h2 className={styles.sectiontitle} id="knowledge-composition">Your knowledge</h2><p className={styles.caption}>{p.counts.articles.toLocaleString("en-US")} active articles in My Space.</p><div className={styles.composition} role="img" aria-label={`${p.counts.synced} synced articles and ${p.counts.notes} personal notes`}><div className={styles.synced} style={{width:`${p.counts.articles?p.counts.synced/p.counts.articles*100:0}%`}}/><div className={styles.notes} style={{width:`${p.counts.articles?p.counts.notes/p.counts.articles*100:0}%`}}/></div><div className={styles.legend}><Link className="kh-focus-ring rounded" href={articles("synced")}><i className={styles.dot}/>Synced<strong>{p.counts.synced}</strong></Link><Link className="kh-focus-ring rounded" href={articles("notes")}><i className={`${styles.dot} ${styles.dotSoft}`}/>Personal notes<strong>{p.counts.notes}</strong></Link></div><Link className={`${styles.archive} kh-focus-ring rounded`} href={articles("archived")}><span>Archived articles</span><strong>{p.counts.archived}</strong></Link><p className={styles.small}>Archived articles and drafts are excluded from the active total.</p></section>
  <section aria-labelledby="source-distribution"><h2 className={styles.sectiontitle} id="source-distribution">Where your knowledge lives</h2><p className={styles.caption}>{p.counts.synced} articles across {p.counts.folders} synced folders.</p>{p.sources.map(s=><Link key={s.sourceId} className={`${styles.source} kh-focus-ring`} href={`${base}/knowledge/${s.sourceId}`}><div className={styles.sourceLabel}><span className={styles.sourceName} title={s.name}>{s.name}</span><span className={styles.sourceCount}>{s.articles} articles</span></div><div className={styles.track}><div className={styles.fill} style={{width:`${s.articles/max*100}%`}}/></div><p className={styles.lastSync}>{s.lastSyncedAt?<>Last synced <Timestamp value={s.lastSyncedAt} variant="relative"/></>:"Never synced"}</p></Link>)}{otherCount>0?<Link className={`${styles.source} kh-focus-ring`} href={`${profile}/sync?filter=folders`}><div className={styles.sourceLabel}><span>{otherCount} other folders</span><span className={styles.sourceCount}>{otherArticles} articles</span></div><div className={styles.track}><div className={styles.fill} style={{width:`${otherArticles/max*100}%`}}/></div></Link>:null}{!p.sources.length?<p className={styles.empty}>Your synced folders will appear here.</p>:null}</section></div>
  <section className={styles.activity} aria-labelledby="recent-changes"><div className={styles.sectionhead}><h2 className={styles.sectiontitle} id="recent-changes">Recent changes</h2></div><p className={styles.caption}>Recorded folder changes in the past {p.days} days.</p><div className={styles.changeStats}>{[{name:"Added",count:p.changes.added,filter:"added",Icon:Plus},{name:"Updated",count:p.changes.updated,filter:"updated",Icon:PenLine},{name:"Archived",count:p.changes.archived,filter:"recent-archived",Icon:Archive}].map(({name,count,filter,Icon})=><Link key={name} className={`${styles.change} kh-focus-ring`} href={articles(filter)} aria-label={`${name}: ${count} articles in the past ${p.days} days`}><div className={styles.changeIcon}><Icon size={16} aria-hidden="true"/></div><div><div className={styles.value}>{count}</div><div className={styles.changeName}>{name}</div></div></Link>)}</div><p className={styles.small}>Distinct articles in each category. An article may appear in more than one category.</p>{p.legacyChangesUnavailable?<p role="status" className={styles.legacy}>Older syncs in this period have no article-level history. These counts include recorded changes only.</p>:null}</section>
  <section className={styles.sync} aria-labelledby="sync-overview"><h2 className={styles.sectiontitle} id="sync-overview">Sync overview</h2><p className={styles.caption}>Latest completed attempt for each active folder.</p><div className={styles.syncGrid}>{[{name:"Last sync successful",count:p.sync.successful,filter:"successful",unit:p.sync.successful===1?"folder":"folders",color:""},{name:"Last sync failed",count:p.sync.failed,filter:"failed",unit:p.sync.failed===1?"folder":"folders",color:styles.warning},{name:"Awaiting Apply",count:p.sync.pending,filter:"pending",unit:p.sync.pending===1?"preview":"previews",color:styles.pending}].map(s=><Link key={s.filter} className={`${styles.syncItem} kh-focus-ring`} href={`${profile}/sync?filter=${s.filter}`} aria-label={`${s.name}: ${s.count} ${s.unit}`}><div className={styles.syncLabel}><i className={`${styles.statusDot} ${s.color}`}/>{s.name}</div><div className={styles.syncCount}><b>{s.count}</b>{s.unit}<ArrowRight size={12} aria-hidden="true"/></div></Link>)}</div><p className={styles.small}>Pending previews are counted separately from completed sync attempts.</p>{p.sync.neverSynced>0?<p className={styles.small}>{p.sync.neverSynced} {p.sync.neverSynced===1?"folder has":"folders have"} no completed sync attempt yet.</p>:null}</section>
  <footer className={styles.footer}><span>My Space only · Updated <Timestamp value={p.generatedAt}/></span><ProfileRefresh/></footer>
  <details className={styles.definitions}><summary className="kh-focus-ring">How counts work</summary><dl><dt>Articles</dt><dd>Saved articles in active sources. Drafts and archived articles are excluded. Personal notes include Hub notes and uploaded Markdown.</dd><dt>Archived articles</dt><dd>Archived documents and documents in archived sources, counted once.</dd><dt>Unread updates</dt><dd>Active synced articles with a recorded change on their latest revision that you have not read. Each article is counted once. Older imports without recorded changes are excluded.</dd><dt>Recent changes</dt><dd>Distinct articles added, updated or archived by recorded folder syncs in the past {p.days} × 24 hours. This is separate from the article’s current archived state.</dd><dt>Awaiting Apply</dt><dd>Your unexpired previews without blockers. Existing-source previews must match the current source version. New-folder previews are included.</dd><dt>Updated time</dt><dd>When these statistics were requested. Each folder’s last successful sync time is displayed separately.</dd></dl></details>
 </main>;
}
